"""Structural lint of the generated Unity C# tree.

We can't compile the C# in this environment (no .NET SDK), so this
test acts as a cheap regression gate that catches the kind of
template bugs you can introduce when emitting code with f-strings:
unbalanced braces / parens, multiple namespaces in one file,
forgotten <auto-generated> markers, or accidental name collisions.

If you regenerate the C# tree and these tests fail, the most likely
cause is a template change in
``cadl.codegen.unity_csharp.{runtime_template, contract_emitter}``
that produced syntactically invalid C#.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from cadl.parser import parse
from cadl.codegen.unity_csharp import generate_unity_csharp


EXAMPLE = (
    Path(__file__).parent.parent
    / "examples" / "sos_dsl_robot_delivery.cadl"
)


@pytest.fixture(scope="module")
def out_dir(tmp_path_factory) -> Path:
    sos = parse(EXAMPLE.read_text(encoding="utf-8"))
    target = tmp_path_factory.mktemp("unity-structural")
    generate_unity_csharp(sos, target)
    return target


def _strip(src: str) -> str:
    """Strip line comments, block comments, and string / char
    literals so the leftover punctuation is the actual C# syntax."""
    src = re.sub(r"//[^\n]*", "", src)
    src = re.sub(r"/\*.*?\*/", "", src, flags=re.DOTALL)
    src = re.sub(r'@"(?:[^"]|"")*"', '""', src)
    src = re.sub(r'"(?:[^"\\\n]|\\.)*"', '""', src)
    src = re.sub(r"'(?:[^'\\\n]|\\.)*'", "''", src)
    return src


# ---------------------------------------------------------------------------
# File-level structural invariants
# ---------------------------------------------------------------------------

def _all_cs(out_dir: Path):
    return sorted(out_dir.rglob("*.cs"))


class TestBalanced:
    def test_braces_balanced(self, out_dir):
        for f in _all_cs(out_dir):
            s = _strip(f.read_text(encoding="utf-8"))
            assert s.count("{") == s.count("}"), (
                f"{f.relative_to(out_dir)}: unbalanced braces "
                f"({s.count('{')} vs {s.count('}')})"
            )

    def test_parens_balanced(self, out_dir):
        for f in _all_cs(out_dir):
            s = _strip(f.read_text(encoding="utf-8"))
            assert s.count("(") == s.count(")"), (
                f"{f.relative_to(out_dir)}: unbalanced parens "
                f"({s.count('(')} vs {s.count(')')})"
            )

    def test_brackets_balanced(self, out_dir):
        for f in _all_cs(out_dir):
            s = _strip(f.read_text(encoding="utf-8"))
            assert s.count("[") == s.count("]"), (
                f"{f.relative_to(out_dir)}: unbalanced brackets "
                f"({s.count('[')} vs {s.count(']')})"
            )


class TestNamespace:
    def test_exactly_one_namespace_per_file(self, out_dir):
        for f in _all_cs(out_dir):
            src = f.read_text(encoding="utf-8")
            ns = re.findall(
                r"^namespace\s+([\w.]+)", src, flags=re.MULTILINE
            )
            assert len(ns) == 1, (
                f"{f.relative_to(out_dir)}: expected 1 namespace, got {ns}"
            )
            assert ns[0].startswith("CADL.SosDsl"), (
                f"{f.relative_to(out_dir)}: bad namespace {ns[0]!r}"
            )


class TestAutoGenerated:
    def test_marker_present(self, out_dir):
        for f in _all_cs(out_dir):
            src = f.read_text(encoding="utf-8")
            assert (
                "auto-generated" in src
                or "auto-edited-on-import" in src
            ), f"{f.relative_to(out_dir)}: missing <auto-generated> marker"

    def test_ends_with_newline(self, out_dir):
        for f in _all_cs(out_dir):
            assert f.read_text(encoding="utf-8").endswith("\n"), (
                f"{f.relative_to(out_dir)}: does not end with newline"
            )


class TestNoCollisions:
    def test_state_enums_unique(self, out_dir):
        names: list[str] = []
        for f in _all_cs(out_dir):
            names += re.findall(
                r"public\s+enum\s+(\w+State)\b", f.read_text(encoding="utf-8")
            )
        assert len(set(names)) == len(names), (
            f"duplicate state enums: {names}"
        )

    def test_contract_classes_unique(self, out_dir):
        names: list[str] = []
        for f in _all_cs(out_dir):
            names += re.findall(
                r"public\s+sealed\s+class\s+(\w+Contract)\b",
                f.read_text(encoding="utf-8"),
            )
        assert len(set(names)) == len(names), (
            f"duplicate contract classes: {names}"
        )


class TestPublicTypes:
    def test_each_file_declares_a_public_type(self, out_dir):
        type_re = re.compile(
            r"public\s+(?:sealed\s+|abstract\s+|static\s+|partial\s+)?"
            r"(?:class|struct|enum|interface)\s+\w+"
        )
        for f in _all_cs(out_dir):
            assert type_re.search(f.read_text(encoding="utf-8")), (
                f"{f.relative_to(out_dir)}: no public type declared"
            )
