"""Per-contract C# emitter for the SoS-DSL Unity codegen target.

Produces three files per contract:

  - ``<Cls>State.cs``    — public enum of lifecycle states.
  - ``<Cls>Monitors.cs`` — declarative monitor evaluator (one method
    per monitor id, plus a Tick / OnEvent dispatcher).
  - ``<Cls>Contract.cs`` — IContractInstance implementation: holds
    state, fires transitions on event match or tick deadlines, lifts
    on_violation, owns its monitor evaluator instance.

Naming convention
-----------------
A contract id like ``DELIVERY_SLA`` becomes the C# identifier
``DeliverySla`` (PascalCase, single-token). Spec users who care about
exact naming should pick contract ids that already PascalCase cleanly.
"""

from __future__ import annotations

import re
from typing import Iterable, Tuple

from ...ast_nodes import ContractDef, LifecycleSpec, MonitorDef


# ---------------------------------------------------------------------------
# Naming helpers
# ---------------------------------------------------------------------------

def _csharp_class_name(contract_id: str) -> str:
    """Convert a CADL contract id into a PascalCase C# class name.

    DELIVERY_SLA -> DeliverySla
    delivery-sla -> DeliverySla
    Delivery_Sla -> DeliverySla
    """
    parts = re.split(r'[^A-Za-z0-9]+', contract_id)
    parts = [p for p in parts if p]
    if not parts:
        return "Contract"
    return ''.join(p[:1].upper() + p[1:].lower() for p in parts)


def _csharp_member(name: str) -> str:
    """Convert an arbitrary id into a safe C# member identifier."""
    s = re.sub(r'[^A-Za-z0-9_]', '_', name)
    if not s or s[0].isdigit():
        s = '_' + s
    return s


def _csharp_string(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace(
        '\n', '\\n').replace('\r', '\\r').replace('\t', '\\t') + '"'


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def emit_contract(
    contract: ContractDef,
    namespace: str = "CADL.SosDsl",
) -> Iterable[Tuple[str, str]]:
    cls = _csharp_class_name(contract.id)
    yield f"{cls}State.cs", _emit_state_enum(contract, cls, namespace)
    yield f"{cls}Monitors.cs", _emit_monitors(contract, cls, namespace)
    yield f"{cls}Contract.cs", _emit_contract_class(contract, cls, namespace)


# ---------------------------------------------------------------------------
# State enum
# ---------------------------------------------------------------------------

def _emit_state_enum(contract: ContractDef, cls: str, ns: str) -> str:
    lc = contract.lifecycle or LifecycleSpec()
    states = list(lc.states) or ["Initial"]
    members = ",\n        ".join(_csharp_member(s) for s in states)
    return (
        "// <auto-generated>\n"
        f"//   contract id : {contract.id}\n"
        f"//   states      : {len(states)}\n"
        f"//   transitions : {len(lc.transitions)}\n"
        "// </auto-generated>\n"
        f"namespace {ns} {{\n"
        f"    public enum {cls}State {{\n"
        f"        {members},\n"
        f"    }}\n"
        f"}}\n"
    )


# ---------------------------------------------------------------------------
# Contract class
# ---------------------------------------------------------------------------

def _emit_contract_class(contract: ContractDef, cls: str, ns: str) -> str:
    lc = contract.lifecycle or LifecycleSpec()
    initial = lc.initial or (lc.states[0] if lc.states else "Initial")
    initial_member = _csharp_member(initial)
    # Declaration order with duplicates removed. A set here made the order of
    # the emitted `case` lines vary from run to run (string hashing is
    # randomised per process), so regenerating produced spurious diffs.
    terminal_states = list(dict.fromkeys(lc.terminal))

    is_terminal_body = ",\n            ".join(
        f"{cls}State.{_csharp_member(s)}" for s in terminal_states
    ) or "/* none */"

    # Build a transition table: per-(from-state) list of edges sorted
    # so deadline-bearing transitions come last (informative only).
    transition_cases: list[str] = []
    for tr in lc.transitions:
        ev_lit = _csharp_string(tr.on or "")
        when_block = ""
        if tr.when:
            # Guard failed → skip this transition. Each transition is an
            # independent `if (...) { ...; FireTransition(...); return; }`
            # block (no enclosing loop/switch), so the correct skip is
            # `return;`. Emitting `break;` here produces invalid C#
            # (CS0139: no enclosing loop out of which to break).
            when_block = (
                f"                if (!PredicateEvaluator.Evaluate("
                f"{_csharp_string(tr.when)}, snap)) return;\n"
            )
        from_match = " || ".join(
            f"_state == {cls}State.{_csharp_member(fs)}"
            for fs in tr.from_states
        )
        transition_cases.append(
            f"            // transition: {tr.id}\n"
            f"            if (ev.Name == {ev_lit} && ({from_match})) {{\n"
            f"                var snap = rt.SnapshotFor(this);\n"
            f"{when_block}"
            f"                FireTransition(rt, ev.TMs,\n"
            f"                    transitionId: {_csharp_string(tr.id)},\n"
            f"                    toState: {cls}State.{_csharp_member(tr.to_state)},\n"
            f"                    cause: \"event\");\n"
            f"                return;\n"
            f"            }}\n"
        )

    # Emit deadline arming: when entering a state, look at all
    # outgoing transitions of that state with deadline_ms; arm a
    # timer for each.
    arm_cases: list[str] = []
    for tr in lc.transitions:
        if tr.deadline_ms is None or not tr.on_violation:
            continue
        target_state = (
            tr.on_violation.transition
            if tr.on_violation and tr.on_violation.transition
            else None
        )
        if not target_state:
            continue
        sev = (tr.on_violation.severity if tr.on_violation else "Major") or "Major"
        for fs in tr.from_states:
            arm_cases.append(
                f"            if (newState == {cls}State.{_csharp_member(fs)}) {{\n"
                f"                _deadlines.Add(new Deadline(\n"
                f"                    transitionId: {_csharp_string(tr.id)},\n"
                f"                    deadlineMs: nowMs + {int(tr.deadline_ms)},\n"
                f"                    targetState: {cls}State.{_csharp_member(target_state)},\n"
                f"                    severity: Severity.{sev}));\n"
                f"            }}\n"
            )

    is_terminal_method = (
        "        private bool IsTerminal(" + cls + "State s) {\n"
        "            switch (s) {\n"
        + ''.join(
            f"                case {cls}State.{_csharp_member(s)}: return true;\n"
            for s in terminal_states
        )
        + "                default: return false;\n"
        "            }\n"
        "        }\n"
    )

    # Pre-compute strings that must contain backslash escapes — they
    # cannot live inside f-string expression parts (Python 3.10).
    arm_block = ''.join(arm_cases) if arm_cases else (
        "            // no deadlines declared\n"
    )
    transitions_block = ''.join(transition_cases)

    # Optional reference to monitor evaluator (only emit if the
    # contract has at least one monitor).
    has_monitors = bool(contract.monitors)
    monitor_field = (
        f"        private readonly {cls}Monitors _monitors;\n"
        if has_monitors else ""
    )
    monitor_init = (
        f"            _monitors = new {cls}Monitors(this);\n"
        if has_monitors else ""
    )
    monitor_event = (
        "            _monitors?.OnEvent(ev, rt);\n"
        if has_monitors else ""
    )
    monitor_tick = (
        "            _monitors?.Tick(nowMs, rt);\n"
        if has_monitors else ""
    )

    return f"""// <auto-generated>
//   Source: CADL contract {contract.id}
// </auto-generated>
using System;
using System.Collections.Generic;

namespace {ns} {{

    /// <summary>
    /// Per-instance contract execution for {contract.id}. Drive it
    /// by registering it on a ContractRuntime, then forwarding port
    /// messages via rt.PostEvent and sim ticks via rt.Tick.
    /// </summary>
    public sealed class {cls}Contract : IContractInstance {{

        public string ContractId => {_csharp_string(contract.id)};
        public string InstanceId {{ get; }}
        public {cls}State State => _state;
        public bool Closed {{ get; private set; }}

        private {cls}State _state;
        private readonly List<Deadline> _deadlines = new List<Deadline>();
        private readonly Dictionary<string, object> _instanceWorld =
            new Dictionary<string, object>();
{monitor_field}
        public {cls}Contract(string instanceId, ContractRuntime rt, long nowMs = 0) {{
            if (string.IsNullOrEmpty(instanceId))
                throw new ArgumentException("instanceId must be non-empty");
            InstanceId = instanceId;
            _state = {cls}State.{initial_member};
{monitor_init}
            rt.Emit(new ContractEvent {{
                Kind = ContractEventKind.Lifecycle,
                ContractId = ContractId,
                InstanceId = InstanceId,
                TransitionId = "<open>",
                FromState = string.Empty,
                ToState = _state.ToString(),
                TMs = nowMs,
                Cause = "open",
            }});

            ArmDeadlinesFor(_state, nowMs);
        }}

        public IDictionary<string, object> WorldSnapshot() {{
            // The runtime composes _world (global) + this dict + state.
            var d = new Dictionary<string, object>(_instanceWorld);
            d["state"] = _state.ToString();
            return d;
        }}

        public void SetInstanceField(string key, object value) {{
            if (!string.IsNullOrEmpty(key)) _instanceWorld[key] = value;
        }}

        public void HandleEvent(in PortEvent ev, ContractRuntime rt) {{
            if (Closed) return;
{transitions_block}
{monitor_event}
        }}

        public void Tick(long nowMs, ContractRuntime rt) {{
            if (Closed) return;
            // 1) Expire deadlines
            for (int i = _deadlines.Count - 1; i >= 0; i--) {{
                var d = _deadlines[i];
                if (d.DeadlineMs <= nowMs) {{
                    _deadlines.RemoveAt(i);
                    rt.Emit(new ContractEvent {{
                        Kind = ContractEventKind.Violation,
                        ContractId = ContractId,
                        InstanceId = InstanceId,
                        Norm = d.TransitionId,
                        Severity = d.Severity,
                        TMs = nowMs,
                        DetectedBy = "deadline:" + d.TransitionId,
                    }});
                    JumpToState(rt, d.TargetState, nowMs, "deadline");
                    if (Closed) return;
                }}
            }}
            // 2) Periodic monitors
{monitor_tick}
        }}

        // --- helpers ---

        public void FireTransition(ContractRuntime rt, long tMs,
                                   string transitionId,
                                   {cls}State toState,
                                   string cause) {{
            var oldState = _state;
            _state = toState;

            // cancel any deadline tied to this transition
            for (int i = _deadlines.Count - 1; i >= 0; i--) {{
                if (_deadlines[i].TransitionId == transitionId) _deadlines.RemoveAt(i);
            }}

            rt.Emit(new ContractEvent {{
                Kind = ContractEventKind.Lifecycle,
                ContractId = ContractId,
                InstanceId = InstanceId,
                TransitionId = transitionId,
                FromState = oldState.ToString(),
                ToState = toState.ToString(),
                TMs = tMs,
                Cause = cause,
            }});

            if (IsTerminal(toState)) {{
                Closed = true;
                _deadlines.Clear();
            }} else {{
                ArmDeadlinesFor(toState, tMs);
            }}
        }}

        public void JumpToState(ContractRuntime rt, {cls}State toState,
                                long tMs, string cause) {{
            var oldState = _state;
            _state = toState;
            _deadlines.Clear();
            rt.Emit(new ContractEvent {{
                Kind = ContractEventKind.Lifecycle,
                ContractId = ContractId,
                InstanceId = InstanceId,
                TransitionId = "<jump>",
                FromState = oldState.ToString(),
                ToState = toState.ToString(),
                TMs = tMs,
                Cause = cause,
            }});
            if (IsTerminal(toState)) {{
                Closed = true;
            }} else {{
                ArmDeadlinesFor(toState, tMs);
            }}
        }}

        private void ArmDeadlinesFor({cls}State newState, long nowMs) {{
{arm_block}        }}

{is_terminal_method}

        private struct Deadline {{
            public string TransitionId;
            public long DeadlineMs;
            public {cls}State TargetState;
            public Severity Severity;
            public Deadline(string transitionId, long deadlineMs,
                            {cls}State targetState, Severity severity) {{
                TransitionId = transitionId;
                DeadlineMs = deadlineMs;
                TargetState = targetState;
                Severity = severity;
            }}
        }}
    }}
}}
"""


# ---------------------------------------------------------------------------
# Monitors
# ---------------------------------------------------------------------------

def _emit_monitors(contract: ContractDef, cls: str, ns: str) -> str:
    monitors: list[MonitorDef] = list(contract.monitors)
    if not monitors:
        return (
            "// <auto-generated />\n"
            f"namespace {ns} {{\n"
            f"    /// <summary>No monitors declared for {contract.id}.</summary>\n"
            f"    public sealed class {cls}Monitors {{\n"
            f"        public {cls}Monitors({cls}Contract _) {{ }}\n"
            f"        public void OnEvent(in PortEvent ev, ContractRuntime rt) {{ }}\n"
            f"        public void Tick(long nowMs, ContractRuntime rt) {{ }}\n"
            f"    }}\n"
            f"}}\n"
        )

    eval_methods: list[str] = []
    tick_cases: list[str] = []
    event_cases: list[str] = []

    for m in monitors:
        method = _csharp_member("Eval_" + m.id)
        rule_lit = _csharp_string(m.rule or "")
        target_id = m.on_match.transition if m.on_match else None
        violation_id = (
            (m.on_match.violation if m.on_match else None) or m.id
        )
        sev = (m.on_match.severity if m.on_match else "Major") or "Major"

        # Body: evaluate predicate against snapshot; on match emit a
        # violation, then either fire a transition by id or jump to a
        # state by name (if target is a state) or do nothing.
        target_handling = ""
        if target_id:
            target_handling = (
                f"                // target: {target_id}\n"
                f"                FireTargetForMonitor(rt, nowMs, "
                f"{_csharp_string(target_id)});\n"
            )

        eval_methods.append(
            f"        private void {method}(long nowMs, ContractRuntime rt) {{\n"
            f"            var snap = rt.SnapshotFor(_owner);\n"
            f"            if (!PredicateEvaluator.Evaluate({rule_lit}, snap)) return;\n"
            f"            rt.Emit(new ContractEvent {{\n"
            f"                Kind = ContractEventKind.Violation,\n"
            f"                ContractId = _owner.ContractId,\n"
            f"                InstanceId = _owner.InstanceId,\n"
            f"                Norm = {_csharp_string(violation_id)},\n"
            f"                Severity = Severity.{sev},\n"
            f"                TMs = nowMs,\n"
            f"                DetectedBy = \"monitor:{m.id}\",\n"
            f"            }});\n"
            f"{target_handling}"
            f"        }}\n"
        )

        if (m.sampling and m.sampling.kind == "periodic"
                and m.sampling.period_ms):
            period = int(m.sampling.period_ms)
            tick_cases.append(
                f"            // monitor: {m.id} (periodic {period}ms)\n"
                f"            if (nowMs - _last_{_csharp_member(m.id)} >= {period}) {{\n"
                f"                _last_{_csharp_member(m.id)} = nowMs;\n"
                f"                {method}(nowMs, rt);\n"
                f"            }}\n"
            )
        else:
            event_cases.append(
                f"            // monitor: {m.id} (event)\n"
                f"            {method}(ev.TMs, rt);\n"
            )

    last_fields = "\n".join(
        f"        private long _last_{_csharp_member(m.id)} = long.MinValue / 2;"
        for m in monitors
        if m.sampling and m.sampling.kind == "periodic"
    )
    # Pre-compute defaults containing backslashes (no f-string traps).
    event_block = ''.join(event_cases) if event_cases else (
        "            // no event-driven monitors\n"
    )
    tick_block = ''.join(tick_cases) if tick_cases else (
        "            // no periodic monitors\n"
    )
    eval_block = ''.join(eval_methods)

    return f"""// <auto-generated>
//   Source: CADL contract {contract.id}
//   Monitors: {len(monitors)}
// </auto-generated>
using System.Collections.Generic;

namespace {ns} {{

    /// <summary>
    /// Declarative monitors for {contract.id}. Owned by the
    /// {cls}Contract instance that constructs it; do not instantiate
    /// manually.
    /// </summary>
    public sealed class {cls}Monitors {{
        private readonly {cls}Contract _owner;
{last_fields}

        public {cls}Monitors({cls}Contract owner) {{ _owner = owner; }}

        public void OnEvent(in PortEvent ev, ContractRuntime rt) {{
{event_block}        }}

        public void Tick(long nowMs, ContractRuntime rt) {{
{tick_block}        }}

        // Fire a target transition (by id) or a state jump if the
        // target name matches a state in {cls}State.
        private void FireTargetForMonitor(ContractRuntime rt, long nowMs,
                                          string targetId) {{
            // Try state-name jump first (most common: 'Violated').
            if (System.Enum.TryParse<{cls}State>(targetId, out var target)) {{
                _owner.JumpToState(rt, target, nowMs, "monitor");
                return;
            }}
            // Otherwise interpret as a transition id; the contract
            // class knows how to find and run it.
            // (For v0.1 we only emit the jump form, which covers all
            // examples in Appendix E.)
        }}

{eval_block}    }}
}}
"""
